#ifndef WIFI_CONFIGURATION_H_GUARD
#define WIFI_CONFIGURATION_H_GUARD

#define WIFI_DEFAULT_AP_SSID "无线DAP"
#define WIFI_DEFAULT_AP_PASS "12345678"
#define WIFI_DEFAULT_HOSTNAME "无线DAP"

#define WIFI_DEFAULT_STA_SSID "example_ssid"
#define WIFI_DEFAULT_STA_PASS "12345678"

#endif //WIFI_CONFIGURATION_H_GUARD